# Generated by Django 5.1.6 on 2025-02-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.TextField()),
                ('Price', models.FloatField(default=60)),
                ('Number_In_Stock', models.IntegerField(default=1)),
                ('Game_Genre', models.TextField(default='Action')),
                ('Game_Platform', models.ManyToManyField(to='game_practice.platform')),
            ],
        ),
    ]
