# Generated by Django 5.1.6 on 2025-02-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_practice', '0003_alter_game_game_genre_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Number_In_Stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
